name       : pango
version    : 1.48.1
release    : 36
source     :
    - https://download.gnome.org/sources/pango/1.48/pango-1.48.1.tar.xz : 08c2d550a96559f15fb317d7167b96df57ef743fef946f4e274bd8b6f2918058
homepage   : http://www.pango.org
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : pango (Library for laying out and rendering text)
description: |
    Pango is a library used for laying out and rendering text with an emphasis on internationalization.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(cairo)
    - pkgconfig32(expat)
    - pkgconfig32(fontconfig)
    - pkgconfig32(fribidi)
    - pkgconfig32(freetype2)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(x11)
    - pkgconfig32(xft)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xrender)
    - pkgconfig(gtk-doc)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi
    %meson_configure -Dgtk_doc=true -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja check || :
