name       : pango
version    : 1.40.14
release    : 18
source     :
    - https://download.gnome.org/sources/pango/1.40/pango-1.40.14.tar.xz : 90af1beaa7bf9e4c52db29ec251ec4fd0a8f2cc185d521ad1f88d01b3a6a17e3
homepage   : http://www.pango.org
license    : LGPL-2.0
component  : desktop.library
summary    : pango (Library for laying out and rendering text)
description: |
    Pango is a library used for laying out and rendering text with an emphasis on internationalization.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(cairo)
    - pkgconfig32(expat)
    - pkgconfig32(fontconfig)
    - pkgconfig32(freetype2)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(xft)
    - pkgconfig32(xshmfence)
setup      : |
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
