name       : pango
version    : 1.40.13
release    : 17
source     :
    - https://download.gnome.org/sources/pango/1.40/pango-1.40.13.tar.xz : f84e98db1078772ff4935b40a1629ff82ef0dfdd08d2cbcc0130c8c437857196
homepage   : http://www.pango.org
license    : LGPL-2.0
component  : desktop.library
summary    : pango (Library for laying out and rendering text)
description: |
    Pango is a library used for laying out and rendering text with an emphasis on internationalization.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(cairo)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(fontconfig)
    - pkgconfig32(xft)
    - pkgconfig32(xshmfence)
    - pkgconfig32(freetype2)
    - pkgconfig32(expat)
    - pkgconfig32(gobject-2.0)
setup      : |
    %patch -p1 < $pkgfiles/Unbork-Char-Break.patch
    %configure --prefix=/usr --disable-static
build      : |
    %make
install    : |
    %make_install
