name       : pango
version    : 1.42.2
release    : 26
source     :
    - https://download.gnome.org/sources/pango/1.42/pango-1.42.2.tar.xz : b1e416b4d40416ef6c8224cf146492b86848703264ba88f792290992cf3ca1e2
homepage   : http://www.pango.org
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : pango (Library for laying out and rendering text)
description: |
    Pango is a library used for laying out and rendering text with an emphasis on internationalization.
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig32(cairo)
    - pkgconfig32(expat)
    - pkgconfig32(fontconfig)
    - pkgconfig32(fribidi)
    - pkgconfig32(freetype2)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(x11)
    - pkgconfig32(xft)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xrender)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check || :
