name       : pango
version    : 1.40.12
release    : 15
source     :
    - http://ftp.acc.umu.se/pub/GNOME/sources/pango/1.40/pango-1.40.12.tar.xz : 75f1a9a8e4e2b28cbc078b50c1fa927ee4ded994d1ade97c5603e2d1f3161cfc
homepage   : http://www.pango.org
license    :
    - LGPL-2.0
summary    : pango (Library for laying out and rendering text)
component  : desktop.library
builddeps  :
    - pkgconfig32(cairo)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(fontconfig)
    - pkgconfig32(xft)
    - pkgconfig32(xshmfence)
    - pkgconfig32(freetype2)
    - pkgconfig32(expat)
    - pkgconfig32(gobject-2.0)
emul32     : yes
optimize   : speed
description: |
    Pango is a library used for laying out and rendering text with an emphasis on internationalization.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
