name       : pango
version    : 1.50.12
release    : 52
source     :
    - https://download.gnome.org/sources/pango/1.50/pango-1.50.12.tar.xz : caef96d27bbe792a6be92727c73468d832b13da57c8071ef79b9df69ee058fe3
homepage   : http://www.pango.org
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : pango (Library for laying out and rendering text)
description: |
    Pango is a library used for laying out and rendering text with an emphasis on internationalization.
emul32     : yes
optimize   :
    - speed
    - lto
builddeps  :
    - pkgconfig32(cairo)
    - pkgconfig32(expat)
    - pkgconfig32(fontconfig)
    - pkgconfig32(fribidi)
    - pkgconfig32(freetype2)
    - pkgconfig32(gobject-2.0)
    - pkgconfig32(harfbuzz)
    - pkgconfig32(json-glib-1.0)
    - pkgconfig32(x11)
    - pkgconfig32(xft)
    - pkgconfig32(xshmfence)
    - pkgconfig32(xrender)
    - pkgconfig(gtk-doc)
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        build_gobject="disabled"
    else
        build_gobject="enabled"
    fi
    %meson_configure -Dgtk_doc=false -Dintrospection=$build_gobject
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja check || :
